### ISSUE TITLE
update entities with string primary key

### ISSUE THREAD

**Issue by nekufa** [tarantool-php/mapper#16]
```
$conn = $this->findOrFail('connection', ['uuid' => $uuid]);
$conn->gateway = $gateway;
$conn->socket = $socket;
$conn->save();
```

produces insert request, uuid is string

**Comment by zilveer** [comment]
can u clarify what you mean with this please?

**Comment by nekufa** [comment]
hello, i mean that mapper now works only with unsigned primary keys and if primary key is string something goes wrong. in example above a use uuid as a primary key and when update operations is performed - you'll see an error.

**Comment by nekufa** [comment]
is not reproduced, covered with test now
