### ISSUE TITLE
Docs issue, $globalSpace->id is: Trying to get property 'id' of non-object

### ISSUE THREAD

**Issue by zilveer** [tarantool-php/mapper#17]
Hi,
first of all thanks for a great plugin!
But it seems to me that the docs isnt "up-to-date".

For example
`$globalSpace = $taraMapper->find('_space', ['name' => '_space']);
echo $globalSpace->id; // 280
`
gives me
`Trying to get property 'id' of non-object`

I dumped the object, and its structure gives me:
`array (size=1)
  0 => 
    object(Tarantool\Mapper\Entity)[600]
      public 'id' => int 280`

So proper outputting the data in this case it:
`$globalSpace[0]->id;` which ouputs `280`

I assume since Tarantool has been upgraded the Docs needs to be updated here as well.

Once again, thanks for such a great repo!

regards Zilveer

**Comment by nekufa** [comment]
Hello, @zilveer, thanks for your feedback!
There was a typo in documentation, thanks!

**Comment by zilveer** [comment]
Perfect it works good now!
